import React, { useEffect, useState } from 'react';
import { Layout, Row, Col, Typography, Card, Button, message } from 'antd';
import { ShoppingCartOutlined, FrownOutlined } from '@ant-design/icons'; // Import icons
import axios from 'axios';
import { useNavigate } from 'react-router-dom'; // Import useNavigate for routing
import './ExplorePlan.css';

const { Title, Paragraph } = Typography;
const { Content } = Layout;

const ExplorePlan = () => {
  const [plans, setPlans] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Retrieve vendor_Id from localStorage
  const vendorId = localStorage.getItem('vendor_Id');
  
  // Initialize the useNavigate hook
  const navigate = useNavigate();

  useEffect(() => {
    const fetchPlansByVendor = async () => {
      try {
        if (!vendorId) {
          message.error('Vendor ID is missing.');
          return;
        }

        const response = await axios.get(`http://localhost:5272/api/SubscriptionPlans/vendor/${vendorId}`);
        
        // Check if the response contains no plans
        if (response.data && response.data.length === 0) {
          setError('No subscription plans available for this vendor.');
        } else {
          setPlans(response.data);
        }
      } catch (error) {
        console.error('Error fetching plans:', error);
        setError('Failed to load subscription plans.');
      } finally {
        setLoading(false);
      }
    };

    fetchPlansByVendor(); // Fetch the plans based on the vendorId
  }, [vendorId]); // Re-run when vendorId changes

  const handleSubscribe = async (plan) => {
    // Retrieve the user ID from localStorage or context
    const userId = localStorage.getItem('user_Id');
    
    if (!userId) {
      message.error('User ID is missing. Please log in again.');
      return;
    }
  
    // Prepare the payment object
    const paymentData = {
      payment_Id: 0, // Assuming this will be generated by the backend
      user_Id: parseInt(userId, 10),
      plan_Id: plan.plan_Id,
      amount: plan.price || 0, // Ensure a fallback value
      payment_Date: new Date().toISOString(),
      payment_Method: 'Online', // Example payment method, adjust as needed
      transaction_Id: `txn_${Date.now()}`, // Generate a unique transaction ID
      payment_Status: 'Success', // Initial status
    };
  
    try {
      // Make a POST request to create the payment
      const response = await axios.post('http://localhost:5272/api/Payments', paymentData);
  
      if (response.status === 201) {
        message.success('Subscription successful!');
        // Navigate to a success or plan details page
        navigate('/USP', { state: { plan } });
      } else {
        throw new Error('Failed to create payment.');
      }
    } catch (error) {
      console.error('Error during subscription:', error);
      message.error('Failed to subscribe. Please try again.');
    }
  };
 

  return (
    <Layout className="explore-plan-page">
      <Content className="explore-plan-content">
        <Title level={2} className="explore-plan-title">
          Explore Our Subscription Plans
        </Title>
        
        {loading ? (
          <Title level={4}>Loading plans...</Title>
        ) : error ? (
          <Row justify="center" align="middle" style={{ color: 'red', padding: '20px' }}>
            <FrownOutlined style={{ fontSize: '40px', marginRight: '10px' }} />
            <Title level={4} style={{ color: 'red' }}>{error}</Title>
          </Row>
        ) : (
          <Row gutter={[16, 16]} justify="center">
            {plans.map((plan) => (
              <Col xs={24} sm={12} md={8} key={plan.plan_Id}>
                <Card
                  hoverable
                  className="explore-plan-card"
                  actions={[
                    <Button
                      type="primary"
                      icon={<ShoppingCartOutlined />}
                      className="explore-plan-button"
                      onClick={() => handleSubscribe(plan)}
                    >
                      Subscribe Now
                    </Button>,
                  ]}
                >
                  <Title level={4} className="explore-plan-card-title">{plan.plan_Name}</Title>
                  <Paragraph className="explore-plan-price">{plan.price ? ` ₹${plan.price}` : 'Contact for Pricing'}</Paragraph>
                  <Paragraph className="explore-plan-description">{plan.description || 'No description available'}</Paragraph>
                  <Paragraph className="plan-features">Features: {plan.features || 'No features listed'}</Paragraph>
                  <Paragraph className="plan-duration">Duration: {plan.duration_In_Days} days</Paragraph>
                  <Paragraph className="plan-status">{plan.is_Active ? 'Active' : 'Inactive'}</Paragraph>
                </Card>
              </Col>
            ))}
          </Row>
        )}
      </Content>
    </Layout>
  );
};

export default ExplorePlan;
